"""empty message

Revision ID: b0edb7d4f81e
Revises: df668b548dc4
Create Date: 2024-12-10 04:31:52.290217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0edb7d4f81e'
down_revision = 'df668b548dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_email', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('farmer_email')

    # ### end Alembic commands ###
